version: "2"

services:
  zookeeper-server:
    container_name: zookeper
    image: "bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zoo:/bitnami/zookeeper
  kafka-server1:
    volumes:
      - kaf:/bitnami/kafka
    container_name: kafka
    hostname: kafka
    image: "bitnami/kafka:2.4.0"
    ports:
      - "6666:6666"
    environment:
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
      - KAFKA_CFG_NUM_PARTITIONS=4
      - KAFKA_CREATE_TOPICS=test5:10:1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:6666
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://domain.com:6666
    depends_on:
      - zookeeper-server
volumes:
  kaf:
  zoo:
